/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import type { OrderItem } from './orderItem';
import type { ReceiveType } from './receiveType';

export interface UpdateReserveOrderDetailDto {
  clientAddrId?: string;
  clientCardId: string;
  clientPhoneNum?: string;
  couponId?: string;
  customerAddr?: string;
  driverTip?: number;
  lat?: number;
  lng?: number;
  note?: string;
  orderItems?: OrderItem[];
  receiveType?: ReceiveType;
  usePointAmount?: number;
}
