/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * OLHSO API
 * The OLHSO API description
 * OpenAPI spec version: 0.1
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  AvailableReservationControllerGetAvailableReservationSlotListParams,
  AvailableSlotList
} from '../../model'



  /**
 * @summary 예약 가능한 슬롯 조회
 */
export const availableReservationControllerGetAvailableReservationSlotList = <TData = AxiosResponse<AvailableSlotList[]>>(
    params?: AvailableReservationControllerGetAvailableReservationSlotListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/olhso/available-reservation`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
export type AvailableReservationControllerGetAvailableReservationSlotListResult = AxiosResponse<AvailableSlotList[]>
